// Package domain defines the core types for the modeloff application.
package domain

import (
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"iter"
	"strings"
	"time"

	"github.com/laney/modeloff/internal/set"
	orderedmap "github.com/wk8/go-ordered-map/v2"
)

// InstanceID is a stable per-session identifier for an actor on the
// server. The human user's instance has an empty InstanceID; every
// model instance is assigned a unique one via GenerateInstanceID.
type InstanceID string

// GenerateInstanceID returns a random 8-byte hex string suitable for
// use as a stable instance identifier.
func GenerateInstanceID() InstanceID {
	var b [8]byte
	_, _ = rand.Read(b[:])

	return InstanceID(hex.EncodeToString(b[:]))
}

// PersonaOrigin distinguishes how a persona was created.
type PersonaOrigin string

const (
	// PersonaGenerated marks a persona that was generated by the small model.
	PersonaGenerated PersonaOrigin = "generated"

	// PersonaUser marks a persona that was defined by the user.
	PersonaUser PersonaOrigin = "user"
)

// Persona describes a character that can be assigned to a model instance.
type Persona struct {
	ID          string        `json:"id"`
	Description string        `json:"description"`
	Origin      PersonaOrigin `json:"origin"`
}

// Nick represents a user or model nickname in the system.
type Nick string

// ChannelPrefix is the prefix used for channel names.
const ChannelPrefix = "#"

// ChannelName represents a chat channel name (with # prefix).
type ChannelName string

// NormaliseChannelName ensures a channel name has the standard #
// prefix. Names that already start with # are returned unchanged.
func NormaliseChannelName(name ChannelName) ChannelName {
	if !strings.HasPrefix(string(name), ChannelPrefix) {
		return ChannelName(ChannelPrefix + string(name))
	}

	return name
}

// ModelID represents an OpenRouter model identifier (e.g. "anthropic/claude-3-haiku").
type ModelID string

// ChannelKind distinguishes channels from direct messages.
type ChannelKind int

// ChannelKind values distinguish between multi-user channels and
// one-to-one direct message conversations.
const (
	// KindChannel is a named channel that multiple users and models
	// can join (prefixed with # in the UI).
	KindChannel ChannelKind = iota

	// KindDM is a private conversation between the user and a
	// single model instance.
	KindDM

	// KindStatus is the per-session "server window" channel that
	// holds connection events, autojoin progress, and dispatch
	// errors. There is exactly one of these and it cannot be parted.
	KindStatus
)

// StatusChannelName is the reserved channel name of the per-session
// status channel. It uses an IRC-style local-channel prefix to make
// it visually distinct from regular channels and impossible to
// collide with a user-created name (`/join` normalises bare names to
// `#`-prefixed).
const StatusChannelName ChannelName = "&modeloff"

// Channel represents a chat channel or direct message conversation.
type Channel struct {
	Name       ChannelName
	Kind       ChannelKind
	Topic      string
	TopicSetBy Nick
	TopicSetAt time.Time
	Members    MemberList
	Created    time.Time
}

// DisplayName returns the channel name formatted for display. DM
// channels are prefixed with @ instead of shown as bare names. The
// status channel renders as its reserved name so the sidebar keeps the
// IRC-convention cue that it is not a user-created room.
func (ch Channel) DisplayName() string {
	switch ch.Kind {
	case KindDM:
		return "@" + string(ch.Name)
	case KindStatus:
		return string(StatusChannelName)
	}

	return string(ch.Name)
}

// Instance represents an actor on the IRC server. Both the human
// user and model instances share this type. The human user has an
// empty ModelID.
type Instance struct {
	InstanceID InstanceID
	Nick       Nick
	ModelID    ModelID
	Persona    string
	Channels   *orderedmap.OrderedMap[ChannelName, time.Time]
}

// IsModel reports whether the instance is a model (as opposed to
// the human user).
func (i Instance) IsModel() bool { return i.ModelID != "" }


// NickMode represents a user's privilege level in a channel, following
// IRC conventions.
type NickMode int

const (
	// ModeNone indicates no special privileges.
	ModeNone NickMode = iota

	// ModeVoice indicates the user has voice (+), shown as "+nick".
	ModeVoice

	// ModeOp indicates the user is a channel operator (@), shown as
	// "@nick".
	ModeOp
)

// String returns the IRC-style prefix for the mode: "@" for op, "+"
// for voice, or "" for none.
func (m NickMode) String() string {
	switch m {
	case ModeOp:
		return "@"
	case ModeVoice:
		return "+"
	default:
		return ""
	}
}

// IRCMode returns the IRC mode-change string for the mode, e.g. "+v"
// for voice and "+o" for op.
func (m NickMode) IRCMode() string {
	switch m {
	case ModeOp:
		return "+o"
	case ModeVoice:
		return "+v"
	default:
		return ""
	}
}

// Member pairs a nick with its channel mode for display in the nick
// list. InstanceID is the stable per-session identity that survives
// nick changes; the human user carries an empty InstanceID.
type Member struct {
	InstanceID InstanceID `json:"instance_id,omitempty"`
	Nick       Nick       `json:"nick"`
	Mode       NickMode   `json:"mode"`
}

func (m Member) String() string {
	return m.Mode.String() + string(m.Nick)
}

// memberLess defines the display order for members: higher modes
// first (op > voice > none), then alphabetically by nick within
// each mode, with InstanceID as a final tiebreaker so that distinct
// instances that briefly share the same (mode, nick) key do not
// collide inside the sorted set.
func memberLess(a, b Member) bool {
	if a.Mode != b.Mode {
		return a.Mode > b.Mode
	}

	if a.Nick != b.Nick {
		return a.Nick < b.Nick
	}

	return a.InstanceID < b.InstanceID
}

// MemberList is a sorted set of channel members ordered by mode
// then nick. The sort is maintained at insertion time so iteration
// and positional access are always free of re-sorting. A parallel
// map keyed by InstanceID backs O(1) identity lookups.
type MemberList struct {
	members *set.Sorted[Member]
	byID    map[InstanceID]Member
}

// NewMemberList creates an empty member list.
func NewMemberList() MemberList {
	return MemberList{
		members: set.NewSorted(memberLess),
		byID:    make(map[InstanceID]Member),
	}
}

// ensureInit lazily initialises the underlying storage so that the
// zero value of MemberList remains usable.
func (ml *MemberList) ensureInit() {
	if ml.members == nil {
		ml.members = set.NewSorted(memberLess)
	}

	if ml.byID == nil {
		ml.byID = make(map[InstanceID]Member)
	}
}

// Add inserts a member identified by instanceID with the given nick
// as a regular (unprivileged) member. The empty instanceID marks the
// human user; because storage is keyed by instance id there can only
// ever be one such entry. Adding with an existing instance id
// updates the stored nick while preserving the current mode (so
// add-with-rename is idempotent).
func (ml *MemberList) Add(instanceID InstanceID, nick Nick) {
	ml.ensureInit()

	m := Member{InstanceID: instanceID, Nick: nick, Mode: ModeNone}

	if cur, ok := ml.byID[instanceID]; ok {
		ml.members.Remove(cur)
		m.Mode = cur.Mode
	}

	ml.members.Insert(m)
	ml.byID[instanceID] = m
}

// Remove deletes the given member. Identity is taken from
// InstanceID; the Mode and Nick on the argument are ignored so that
// callers holding a stale mode can still remove a member cleanly.
func (ml *MemberList) Remove(m Member) {
	if ml.members == nil {
		return
	}

	cur, ok := ml.byID[m.InstanceID]
	if !ok {
		return
	}

	ml.members.Remove(cur)
	delete(ml.byID, m.InstanceID)
}

// SetMode changes a member's privilege level by instance id. This
// removes and re-inserts the member since mode is part of the sort
// key. Setting the mode of an unknown instance is a no-op.
func (ml *MemberList) SetMode(instanceID InstanceID, mode NickMode) {
	if ml.members == nil {
		return
	}

	cur, ok := ml.byID[instanceID]
	if !ok {
		return
	}

	ml.members.Remove(cur)

	updated := Member{InstanceID: instanceID, Nick: cur.Nick, Mode: mode}
	ml.members.Insert(updated)
	ml.byID[instanceID] = updated
}

// SetModeByNick is a display-layer convenience that forwards to
// SetMode after resolving the nick to its instance id. Wire code
// that only has a nick in hand (e.g. ChanServ-style commands) uses
// this. It is a no-op if the nick is unknown.
func (ml *MemberList) SetModeByNick(nick Nick, mode NickMode) {
	if ml.members == nil {
		return
	}

	m, ok := ml.GetByNick(nick)
	if !ok {
		return
	}

	ml.SetMode(m.InstanceID, mode)
}

// RenameTo updates the stored nick for the given instance id,
// preserving the existing mode. The underlying sorted set is
// re-keyed in place (remove + insert) because Nick participates in
// the sort order. It is a no-op if the instance id is unknown.
func (ml *MemberList) RenameTo(instanceID InstanceID, newNick Nick) {
	if ml.members == nil {
		return
	}

	cur, ok := ml.byID[instanceID]
	if !ok {
		return
	}

	ml.members.Remove(cur)

	updated := Member{InstanceID: instanceID, Nick: newNick, Mode: cur.Mode}
	ml.members.Insert(updated)
	ml.byID[instanceID] = updated
}

// GetByID returns the member for the given instance id.
func (ml MemberList) GetByID(instanceID InstanceID) (Member, bool) {
	if ml.byID == nil {
		return Member{}, false
	}

	m, ok := ml.byID[instanceID]

	return m, ok
}

// HasID reports whether a member exists with the given instance id.
func (ml MemberList) HasID(instanceID InstanceID) bool {
	_, ok := ml.GetByID(instanceID)

	return ok
}

// GetByNick finds a member by display nick. It is intended for
// display-layer lookups (e.g. resolving a typed command argument);
// identity-bearing code should prefer GetByID.
func (ml MemberList) GetByNick(nick Nick) (Member, bool) {
	if ml.members == nil {
		return Member{}, false
	}

	for m := range ml.members.All() {
		if m.Nick == nick {
			return m, true
		}
	}

	return Member{}, false
}

// HasNick reports whether any member currently displays the given
// nick.
func (ml MemberList) HasNick(nick Nick) bool {
	_, ok := ml.GetByNick(nick)

	return ok
}

// Len returns the total number of members.
func (ml MemberList) Len() int {
	return ml.members.Len()
}

// GetAt returns the member at the given display position.
func (ml MemberList) GetAt(index int) (Member, bool) {
	return ml.members.GetAt(index)
}

// SortedSet returns the underlying sorted set. This exposes the
// btree directly for use by the generic sidebar.
func (ml MemberList) SortedSet() *set.Sorted[Member] {
	return ml.members
}

// All yields every member in display order.
func (ml MemberList) All() iter.Seq2[int, Member] {
	return ml.members.Indexed()
}

// Slice returns all members as a plain slice in display order.
func (ml MemberList) Slice() []Member {
	if ml.Len() == 0 {
		return nil
	}

	out := make([]Member, 0, ml.Len())

	for _, m := range ml.All() {
		out = append(out, m)
	}

	return out
}

// Nicks returns an iterator over just the nicks in display order.
func (ml MemberList) Nicks() iter.Seq[Nick] {
	return func(yield func(Nick) bool) {
		for _, m := range ml.All() {
			if !yield(m.Nick) {
				return
			}
		}
	}
}

// MarshalJSON encodes the member list as a JSON array of members.
func (ml MemberList) MarshalJSON() ([]byte, error) {
	members := make([]Member, 0, ml.Len())

	for _, m := range ml.All() {
		members = append(members, m)
	}

	return json.Marshal(members)
}

// UnmarshalJSON decodes a JSON array of members into the list. An
// empty or null array leaves the backing storage nil so that the
// zero value round-trips cleanly under reflect.DeepEqual; mutating
// methods on the resulting list lazily initialise the underlying
// storage.
func (ml *MemberList) UnmarshalJSON(data []byte) error {
	var members []Member
	if err := json.Unmarshal(data, &members); err != nil {
		return err
	}

	if len(members) == 0 {
		*ml = MemberList{}
		return nil
	}

	*ml = NewMemberList()

	for _, m := range members {
		ml.members.Insert(m)
		ml.byID[m.InstanceID] = m
	}

	return nil
}
