// Package domain defines the core types for the modeloff application.
package domain

import (
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"iter"
	"strings"
	"sync"
	"time"

	"github.com/laney/modeloff/internal/set"
	orderedmap "github.com/wk8/go-ordered-map/v2"
)

// InstanceID is a stable per-session identifier for an actor on the
// server. The human user's instance has an empty InstanceID; every
// model instance is assigned a unique one via GenerateInstanceID.
//
// InstanceID is the serialised wire form of identity (store columns,
// event-log records). Within the process the canonical handle is
// `*Instance`; callers compare instances by pointer identity.
type InstanceID string

// GenerateInstanceID returns a random 8-byte hex string suitable for
// use as a stable instance identifier.
func GenerateInstanceID() InstanceID {
	var b [8]byte
	_, _ = rand.Read(b[:])

	return InstanceID(hex.EncodeToString(b[:]))
}

// PersonaOrigin distinguishes how a persona was created.
type PersonaOrigin string

const (
	// PersonaGenerated marks a persona that was generated by the small model.
	PersonaGenerated PersonaOrigin = "generated"

	// PersonaUser marks a persona that was defined by the user.
	PersonaUser PersonaOrigin = "user"
)

// Persona describes a character that can be assigned to a model instance.
type Persona struct {
	ID          string        `json:"id"`
	Description string        `json:"description"`
	Origin      PersonaOrigin `json:"origin"`
}

// Nick represents a user or model nickname in the system.
type Nick string

// ChannelPrefix is the prefix used for channel names.
const ChannelPrefix = "#"

// ChannelName represents a chat channel name (with # prefix).
type ChannelName string

// NormaliseChannelName ensures a channel name has the standard #
// prefix. Names that already start with # are returned unchanged.
func NormaliseChannelName(name ChannelName) ChannelName {
	if !strings.HasPrefix(string(name), ChannelPrefix) {
		return ChannelName(ChannelPrefix + string(name))
	}

	return name
}

// ModelID represents an OpenRouter model identifier (e.g. "anthropic/claude-3-haiku").
type ModelID string

// ChannelKind distinguishes channels from direct messages.
type ChannelKind int

// ChannelKind values distinguish between multi-user channels and
// one-to-one direct message conversations.
const (
	// KindChannel is a named channel that multiple users and models
	// can join (prefixed with # in the UI).
	KindChannel ChannelKind = iota

	// KindDM is a private conversation between the user and a
	// single model instance.
	KindDM

	// KindStatus is the per-session "server window" channel that
	// holds connection events, autojoin progress, and dispatch
	// errors. There is exactly one of these and it cannot be parted.
	KindStatus
)

// StatusChannelName is the reserved name the chat-screen uses for
// its local server-window view. It uses an IRC-style local-channel
// prefix to make it visually distinct from regular channels and
// impossible to collide with a user-created name (`/join`
// normalises bare names to `#`-prefixed). The session itself does
// not own a window under this name — it is purely a chat-screen
// rendering target for server-emitted events ([Welcome],
// [Reconnected], [ModelUnavailableError], …).
const StatusChannelName ChannelName = "&modeloff"

// StatusServerName is the server identity emitted on the wire as
// the source of server-originated events (RPL_WELCOME and similar
// numerics, NOTICE-shaped messages). It is the canonical "who is
// the server speaking" string clients render alongside a server
// message.
const StatusServerName Nick = "modeloff"

// InferChannelKind derives a channel's kind from its name alone. It
// is the single source of truth for callers that need to look up a
// channel in a sorted set keyed by `(Kind, Name)` but only have the
// name to hand: the reserved status name is `KindStatus`,
// `#`-prefixed names are `KindChannel`, and bare names are `KindDM`.
func InferChannelKind(name ChannelName) ChannelKind {
	switch {
	case name == StatusChannelName:
		return KindStatus
	case strings.HasPrefix(string(name), ChannelPrefix):
		return KindChannel
	default:
		return KindDM
	}
}

// Instance represents an actor on the IRC server. Both the human
// user and model instances share this type. The human user has an
// empty ModelID.
//
// Instance is an opaque handle: callers hold a `*Instance`, compare
// instances by pointer identity, and observe mutable attributes
// (nick, persona, channels) via the getter methods. Mutable fields
// are guarded by an internal RWMutex so concurrent readers see a
// consistent snapshot; writes (rare: a rename, a persona update, a
// join) take the write lock.
//
// Instance must be constructed via NewUserInstance or
// NewModelInstance. Zero-value Instance is reserved for internal
// wire-format stubs (see MemberList.UnmarshalJSON); do not use it
// elsewhere.
type Instance struct {
	instanceID InstanceID // immutable, set at construction
	ModelID    ModelID    // immutable, set at construction

	mu       sync.RWMutex
	nick     Nick
	persona  string
	channels *orderedmap.OrderedMap[ChannelName, time.Time]
}

// NewUserInstance constructs the human user's Instance. The user
// carries the empty InstanceID as its stable identity marker and no
// ModelID. The channels map is initialised empty.
func NewUserInstance(nick Nick) *Instance {
	return newInstance("", "", nick, "", orderedmap.New[ChannelName, time.Time]())
}

// NewModelInstance constructs a model-backed Instance with the given
// identity, nick, model id, persona, and channels. If channels is
// nil, an empty ordered map is created.
//
// The caller must pass a non-empty InstanceID (use
// GenerateInstanceID). Empty IDs are reserved for the user sentinel
// constructed via NewUserInstance.
func NewModelInstance(id InstanceID, nick Nick, modelID ModelID, persona string, channels *orderedmap.OrderedMap[ChannelName, time.Time]) *Instance {
	if channels == nil {
		channels = orderedmap.New[ChannelName, time.Time]()
	}

	return newInstance(id, modelID, nick, persona, channels)
}

func newInstance(id InstanceID, modelID ModelID, nick Nick, persona string, channels *orderedmap.OrderedMap[ChannelName, time.Time]) *Instance {
	return &Instance{
		instanceID: id,
		ModelID:    modelID,
		nick:       nick,
		persona:    persona,
		channels:   channels,
	}
}

// ID returns the stable InstanceID. This is the serialisation form
// of identity; within the process, callers should prefer pointer
// identity. Used by the store, event-log, and observability layers.
// Returns the empty InstanceID on a nil receiver, matching the
// zero-value shape of Nick/Persona/Channels.
func (i *Instance) ID() InstanceID {
	if i == nil {
		return ""
	}

	return i.instanceID
}

// Nick returns the instance's current display nick. The nick is
// mutable (via SetNick) so multiple calls may return different
// values after a rename.
func (i *Instance) Nick() Nick {
	if i == nil {
		return ""
	}

	i.mu.RLock()
	defer i.mu.RUnlock()

	return i.nick
}

// SetNick updates the display nick under the write lock. Backend-
// only; the frontend observes renames through `NickChangeEvent`
// rather than by mutating the handle directly.
func (i *Instance) SetNick(nick Nick) {
	i.mu.Lock()
	defer i.mu.Unlock()

	i.nick = nick
}

// Persona returns the current persona description.
func (i *Instance) Persona() string {
	if i == nil {
		return ""
	}

	i.mu.RLock()
	defer i.mu.RUnlock()

	return i.persona
}

// SetPersona updates the persona description under the write lock.
func (i *Instance) SetPersona(persona string) {
	i.mu.Lock()
	defer i.mu.Unlock()

	i.persona = persona
}

// Channels returns a read-only snapshot of the channels-joined-time
// map. The returned map is a clone; callers may read or iterate it
// without coordinating with writers. Mutations must go through
// MutateChannels.
func (i *Instance) Channels() *orderedmap.OrderedMap[ChannelName, time.Time] {
	if i == nil {
		return nil
	}

	i.mu.RLock()
	defer i.mu.RUnlock()

	return cloneChannels(i.channels)
}

// MutateChannels applies fn to the channels map under the write
// lock. fn sees the live map and is free to mutate it in place.
// Readers that raced with the mutation observe either the pre- or
// post-state, never a partial one.
func (i *Instance) MutateChannels(fn func(*orderedmap.OrderedMap[ChannelName, time.Time])) {
	i.mu.Lock()
	defer i.mu.Unlock()

	if i.channels == nil {
		i.channels = orderedmap.New[ChannelName, time.Time]()
	}

	fn(i.channels)
}

// cloneChannels returns a shallow copy of the ordered channel/join-
// time map. The new map is safe to mutate; the original must be
// treated as frozen.
func cloneChannels(src *orderedmap.OrderedMap[ChannelName, time.Time]) *orderedmap.OrderedMap[ChannelName, time.Time] {
	clone := orderedmap.New[ChannelName, time.Time]()

	if src == nil {
		return clone
	}

	for pair := src.Oldest(); pair != nil; pair = pair.Next() {
		clone.Set(pair.Key, pair.Value)
	}

	return clone
}

// IsModel reports whether the instance is a model (as opposed to
// the human user).
func (i *Instance) IsModel() bool { return i.ModelID != "" }

// instanceJSON is the wire format for `Instance`. It mirrors the
// pre-handle struct so the store-column and existing test fixtures
// continue to deserialise unchanged.
type instanceJSON struct {
	InstanceID InstanceID                                     `json:"InstanceID"`
	Nick       Nick                                           `json:"Nick"`
	ModelID    ModelID                                        `json:"ModelID"`
	Persona    string                                         `json:"Persona"`
	Channels   *orderedmap.OrderedMap[ChannelName, time.Time] `json:"Channels"`
}

// MarshalJSON implements json.Marshaler. The read-lock is held for
// the duration of the snapshot build so concurrent mutations do not
// produce a torn record.
func (i *Instance) MarshalJSON() ([]byte, error) {
	if i == nil {
		return []byte("null"), nil
	}

	i.mu.RLock()
	snapshot := instanceJSON{
		InstanceID: i.instanceID,
		Nick:       i.nick,
		ModelID:    i.ModelID,
		Persona:    i.persona,
		Channels:   cloneChannels(i.channels),
	}
	i.mu.RUnlock()

	return json.Marshal(snapshot)
}

// UnmarshalJSON implements json.Unmarshaler.
func (i *Instance) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return nil
	}

	var v instanceJSON
	if err := json.Unmarshal(data, &v); err != nil {
		return fmt.Errorf("unmarshal instance: %w", err)
	}

	channels := v.Channels
	if channels == nil {
		channels = orderedmap.New[ChannelName, time.Time]()
	}

	i.mu.Lock()
	i.instanceID = v.InstanceID
	i.ModelID = v.ModelID
	i.nick = v.Nick
	i.persona = v.Persona
	i.channels = channels
	i.mu.Unlock()

	return nil
}

// NickMode represents a user's privilege level in a channel, following
// IRC conventions.
// Mode is a single RFC 2812 mode flag letter. The same letter
// carries different semantics depending on the target type of the
// carrying [ModeChange]: 'o' on a channel target is channel-op;
// 'o' with no channel target is server-OPER (a user mode).
// `rune` is the natural carrier — IRC mode flags are single ASCII
// letters.
type Mode rune

const (
	// Member modes (RFC 2812 §3.2.3 channel-scoped per-member
	// privileges; also serve as user-mode `+o` per §3.1.5 when
	// the carrying event has no channel target).
	ModeOperator     Mode = 'o'
	ModeChannelVoice Mode = 'v'

	// Channel-attribute modes (RFC 2811 §4.2 / RFC 2812 §3.2.3).
	// Each scopes a behaviour on the channel as a whole: the
	// boolean ones toggle a flag; `+l` and `+k` take a parameter
	// (user-limit, channel key).
	ModeAnonymous  Mode = 'a'
	ModeInviteOnly Mode = 'i'
	ModeModerated  Mode = 'm'
	ModeNoExternal Mode = 'n'
	ModePrivate    Mode = 'p'
	ModeQuiet      Mode = 'q'
	ModeSecret     Mode = 's'
	ModeTopicLock  Mode = 't'
	ModeUserLimit  Mode = 'l'
	ModeKey        Mode = 'k'
)

// MemberMode reports whether the flag is one of the per-member
// modes ([ModeOperator], [ModeChannelVoice]) — the ones whose
// `MODE` form takes a nick target inside a channel. The remaining
// flags are channel attributes whose `MODE` form takes either no
// parameter or a single value.
func (m Mode) MemberMode() bool {
	return m == ModeOperator || m == ModeChannelVoice
}

// IRCString renders a mode flag in the conventional `+x` / `-x`
// shape per the `add` direction. The empty Mode renders as the
// empty string.
func (m Mode) IRCString(add bool) string {
	if m == 0 {
		return ""
	}

	if add {
		return "+" + string(rune(m))
	}

	return "-" + string(rune(m))
}

// NickMode is a per-member display rank used by the nick-list
// renderer for sort ordering and the `@`/`+` prefix. It is a
// display concern distinct from the wire-flag [Mode]; the two
// coexist because the chat-screen sorts members by privilege
// while the wire carries single-letter flags. Use [WireFlag]
// to convert.
type NickMode int

const (
	// ModeNone indicates no special privileges.
	ModeNone NickMode = iota

	// ModeVoice indicates the user has voice (+), shown as "+nick".
	ModeVoice

	// ModeOp indicates the user is a channel operator (@), shown as
	// "@nick".
	ModeOp
)

// String returns the IRC-style prefix for the mode: "@" for op, "+"
// for voice, or "" for none.
func (m NickMode) String() string {
	switch m {
	case ModeOp:
		return "@"
	case ModeVoice:
		return "+"
	default:
		return ""
	}
}

// IRCMode returns the IRC mode-change string for the mode, e.g. "+v"
// for voice and "+o" for op.
func (m NickMode) IRCMode() string {
	switch m {
	case ModeOp:
		return "+o"
	case ModeVoice:
		return "+v"
	default:
		return ""
	}
}

// WireFlag returns the wire-protocol [Mode] letter for this rank,
// suitable for populating [ModeChange.Flag]. The zero value
// [ModeNone] returns the zero [Mode].
func (m NickMode) WireFlag() Mode {
	switch m {
	case ModeOp:
		return ModeOperator
	case ModeVoice:
		return ModeChannelVoice
	default:
		return 0
	}
}

// NickModeFor inverts [NickMode.WireFlag]: it maps a channel-scoped
// wire flag back to its display rank. The zero value is returned
// for any flag that is not a channel-member mode, or when `add` is
// false (the member loses the rank).
func NickModeFor(flag Mode, add bool) NickMode {
	if !add {
		return ModeNone
	}

	switch flag {
	case ModeOperator:
		return ModeOp
	case ModeChannelVoice:
		return ModeVoice
	default:
		return ModeNone
	}
}

// Member pairs an Instance with its channel mode for display in the
// nick list.
//
// Nick is a snapshot of the instance's nick at the time of the last
// Add/RenameTo; it stays consistent within a single render frame
// even as the underlying instance renames. The snapshot is kept in
// sync by MemberList.RenameTo, which is called from
// handleNickChangeEvent. Any code path that mutates Instance.nick
// without emitting NickChangeEvent for every channel the instance
// is in will leave this field stale.
type Member struct {
	Instance *Instance
	Nick     Nick
	Mode     NickMode
}

func (m Member) String() string {
	return m.Mode.String() + string(m.Nick)
}

// Less defines the display order for members: higher modes
// first (op > voice > none), then alphabetically by nick within
// each mode. The final tiebreaker on `Instance.ID()` keeps
// distinct instances with the same mode-and-nick pair from
// colliding inside the sorted set.
func (m Member) Less(other Member) bool {
	if m.Mode != other.Mode {
		return m.Mode > other.Mode
	}

	if m.Nick != other.Nick {
		return m.Nick < other.Nick
	}

	return m.Instance.ID() < other.Instance.ID()
}

// MemberList is a sorted set of channel members ordered by mode
// then nick. The sort is maintained at insertion time so iteration
// and positional access are always free of re-sorting. A parallel
// map keyed by `*Instance` pointer backs O(1) identity lookups.
type MemberList struct {
	members    *set.Sorted[Member]
	byInstance map[*Instance]Member
}

// NewMemberList creates an empty member list.
func NewMemberList() MemberList {
	return MemberList{
		members:    set.NewSorted[Member](),
		byInstance: make(map[*Instance]Member),
	}
}

// ensureInit lazily initialises the underlying storage so that the
// zero value of MemberList remains usable.
func (ml *MemberList) ensureInit() {
	if ml.members == nil {
		ml.members = set.NewSorted[Member]()
	}

	if ml.byInstance == nil {
		ml.byInstance = make(map[*Instance]Member)
	}
}

// Add inserts an instance as a regular (unprivileged) member. The
// snapshot nick in the resulting Member is captured from the
// instance at call time; subsequent renames propagate through
// `RenameTo`. Adding an instance that is already a member updates
// its snapshot nick while preserving the current mode.
func (ml *MemberList) Add(inst *Instance) {
	ml.ensureInit()

	m := Member{Instance: inst, Nick: inst.Nick(), Mode: ModeNone}

	if cur, ok := ml.byInstance[inst]; ok {
		ml.members.Remove(cur)
		m.Mode = cur.Mode
	}

	ml.members.Insert(m)
	ml.byInstance[inst] = m
}

// Remove deletes the given member. Identity is taken from
// `m.Instance`; the Mode and Nick on the argument are ignored so
// that callers holding a stale mode can still remove a member
// cleanly.
func (ml *MemberList) Remove(m Member) {
	if ml.members == nil {
		return
	}

	cur, ok := ml.byInstance[m.Instance]
	if !ok {
		return
	}

	ml.members.Remove(cur)
	delete(ml.byInstance, m.Instance)
}

// RemoveInstance is a convenience for callers that hold the handle
// but not a full Member. It is equivalent to `Remove(Member{Instance:
// inst})`.
func (ml *MemberList) RemoveInstance(inst *Instance) {
	ml.Remove(Member{Instance: inst})
}

// SetMode changes a member's privilege level. This removes and
// re-inserts the member since mode is part of the sort key. Setting
// the mode of an unknown instance is a no-op.
func (ml *MemberList) SetMode(inst *Instance, mode NickMode) {
	if ml.members == nil {
		return
	}

	cur, ok := ml.byInstance[inst]
	if !ok {
		return
	}

	ml.members.Remove(cur)

	updated := Member{Instance: inst, Nick: cur.Nick, Mode: mode}
	ml.members.Insert(updated)
	ml.byInstance[inst] = updated
}

// SetModeByNick is a display-layer convenience that forwards to
// SetMode after resolving the nick to its instance handle. Wire
// code that only has a nick in hand (e.g. ChanServ-style commands)
// uses this. It is a no-op if the nick is unknown.
func (ml *MemberList) SetModeByNick(nick Nick, mode NickMode) {
	if ml.members == nil {
		return
	}

	m, ok := ml.GetByNick(nick)
	if !ok {
		return
	}

	ml.SetMode(m.Instance, mode)
}

// RenameTo updates the snapshot nick for the given instance handle,
// preserving the existing mode. The underlying sorted set is
// re-keyed in place (remove + insert) because Nick participates in
// the sort order. It is a no-op if the instance is not currently a
// member.
//
// RenameTo only updates this MemberList's snapshot — the caller is
// responsible for also calling `inst.SetNick(newNick)` and for
// re-calling `RenameTo` on every other channel the instance is in.
// The session's nick-change path handles this fan-out.
func (ml *MemberList) RenameTo(inst *Instance, newNick Nick) {
	if ml.members == nil {
		return
	}

	cur, ok := ml.byInstance[inst]
	if !ok {
		return
	}

	ml.members.Remove(cur)

	updated := Member{Instance: inst, Nick: newNick, Mode: cur.Mode}
	ml.members.Insert(updated)
	ml.byInstance[inst] = updated
}

// GetByInstance returns the member for the given instance handle.
func (ml MemberList) GetByInstance(inst *Instance) (Member, bool) {
	if ml.byInstance == nil {
		return Member{}, false
	}

	m, ok := ml.byInstance[inst]

	return m, ok
}

// HasInstance reports whether the given instance handle is a
// member.
func (ml MemberList) HasInstance(inst *Instance) bool {
	_, ok := ml.GetByInstance(inst)

	return ok
}

// GetByNick finds a member by display nick. It is intended for
// display-layer lookups (tab completion, resolving a typed command
// argument); identity-bearing code should prefer GetByInstance.
func (ml MemberList) GetByNick(nick Nick) (Member, bool) {
	if ml.members == nil {
		return Member{}, false
	}

	for m := range ml.members.All() {
		if m.Nick == nick {
			return m, true
		}
	}

	return Member{}, false
}

// HasNick reports whether any member currently displays the given
// nick.
func (ml MemberList) HasNick(nick Nick) bool {
	_, ok := ml.GetByNick(nick)

	return ok
}

// Len returns the total number of members.
func (ml MemberList) Len() int {
	return ml.members.Len()
}

// GetAt returns the member at the given display position.
func (ml MemberList) GetAt(index int) (Member, bool) {
	return ml.members.GetAt(index)
}

// SortedSet returns the underlying sorted set. This exposes the
// btree directly for use by the generic sidebar.
func (ml MemberList) SortedSet() *set.Sorted[Member] {
	return ml.members
}

// All yields every member in display order.
func (ml MemberList) All() iter.Seq[Member] {
	return ml.members.All()
}

// Nicks returns an iterator over just the nicks in display order.
func (ml MemberList) Nicks() iter.Seq[Nick] {
	return func(yield func(Nick) bool) {
		for m := range ml.All() {
			if !yield(m.Nick) {
				return
			}
		}
	}
}

// memberJSON is the wire format for a single Member. It records the
// instance id on the wire so the channel can round-trip before the
// store has resolved ids back to canonical `*Instance` handles; the
// store layer provides an `InstanceResolver` when loading to rewrite
// the id back to a pointer.
type memberJSON struct {
	InstanceID InstanceID `json:"instance_id,omitempty"`
	Nick       Nick       `json:"nick"`
	Mode       NickMode   `json:"mode"`
}

// MarshalJSON encodes the member list as a JSON array of members
// keyed by InstanceID on the wire.
func (ml MemberList) MarshalJSON() ([]byte, error) {
	out := make([]memberJSON, 0, ml.Len())

	for m := range ml.All() {
		var id InstanceID
		if m.Instance != nil {
			id = m.Instance.ID()
		}

		out = append(out, memberJSON{InstanceID: id, Nick: m.Nick, Mode: m.Mode})
	}

	return json.Marshal(out)
}

// UnmarshalJSON decodes a JSON array of member records into the
// list. Each record is stored as a stub `*Instance` carrying only
// the serialised id; callers that need canonical handles (the
// session on channel load) rewrite the stubs via
// `MemberList.ResolveInstances`.
func (ml *MemberList) UnmarshalJSON(data []byte) error {
	var records []memberJSON
	if err := json.Unmarshal(data, &records); err != nil {
		return err
	}

	*ml = NewMemberList()

	if len(records) == 0 {
		return nil
	}

	for _, r := range records {
		stub := &Instance{instanceID: r.InstanceID}
		m := Member{Instance: stub, Nick: r.Nick, Mode: r.Mode}

		ml.members.Insert(m)
		ml.byInstance[stub] = m
	}

	return nil
}

// InstanceResolver turns a serialised InstanceID back into the
// canonical `*Instance` handle produced by the store. Returning nil
// for a not-found id indicates "drop this member" — currently used
// only by the store layer when a member row references an instance
// row that has been deleted.
type InstanceResolver func(InstanceID) *Instance

// ResolveInstances rewrites each member's stub `*Instance` (set by
// UnmarshalJSON to carry only the serialised id) to the canonical
// handle returned by resolve. A stub whose id resolves to nil is
// dropped from the list.
//
// This is intended for the store's channel-deserialisation path
// only: the store reads a channel's member-list records from disk,
// then calls ResolveInstances to rewrite the stubs to the canonical
// pointers it owns. Session and UI code never call this directly —
// by the time a Channel surfaces to session the MemberList already
// carries canonical handles.
func (ml *MemberList) ResolveInstances(resolve InstanceResolver) {
	if ml.members == nil {
		return
	}

	rebuilt := set.NewSorted[Member]()
	byInstance := make(map[*Instance]Member, ml.members.Len())

	for m := range ml.All() {
		id := m.Instance.ID()

		canonical := resolve(id)
		if canonical == nil {
			continue
		}

		updated := Member{Instance: canonical, Nick: m.Nick, Mode: m.Mode}
		rebuilt.Insert(updated)
		byInstance[canonical] = updated
	}

	ml.members = rebuilt
	ml.byInstance = byInstance
}
